sudo: false
language: python
python:
  - "2.7"

install:
  - pip install codecov

# Run the unit test
script:
  - coverage run playertest.py

# Push the results back to codecov
after_success:
  - codecov
